Examples/HelloWorldVapor/.gitignore
Examples/HelloWorldVapor/Package.resolved
Examples/HelloWorldVapor/Package.swift
Examples/HelloWorldVapor/Sources/main.swift
README.md
Sources/ContainerImageBuilderPluginDocumentation/Documentation.docc/ContainerImageBuilderPlugin.md

Having a simple "getting started" example is helpful for new users.
Adds the first example, using Vapor, and links it into the documentation.
New users can start from a tested starting point.
Built and deployed the example locally, and ran the soundness checks.

Examples: Add a Hello World example

---

Package.swift

The `swiftLanguageVersions` parameter is deprecated and has been replaced by `swiftLanguageModes`
Replace `swiftLanguageVersions` with `swiftLanguageModes`.
Swift Package Manager no longer prints a deprecation warning during the build.
Built and tested the Vapor example project using the updated plugin.

Package: Replace deprecated `swiftLanguageVersions` parameter

---

.github/workflows/pull_request.yml
.spi.yml
Package.swift

The containertool target will not build with the `nightly` Linux image currently being used for some of the CI tests.   Falling back to Swift Language Mode v5 allows all tests to be enabled.
The containertool target is declared to use the v5 language mode.
The `api_breakage_check` test is enabled.
`containertool` will build using Linux images, and the breakage checks will run.
Built locally and verified that the new tests pass using `act pull_request`.

Use v5 language mode for containertool

---

.github/workflows/pull_request.yml
Vendor/github.com/apple/swift-package-manager/Sources/Basics/AuthorizationProvider.swift

Much of the project passes the Swift 6 language mode checks, so we should run them on each pull request to prevent regressions.
Enable the Swift 6 language mode check job in the pull request workflow and fix the errors it finds.
The Swift 6 checks will pass.
Ran the checks locally using `act pull_request`.

ci: Enable Swift 6 Language Mode checks

---

Examples/HelloWorldVapor/Package.resolved
NOTICE.txt

async-http-client 1.23.0 compiles with the Swift Static Linux SDK again, so it is no longer necessary to pin to 1.22.1
Updated `Package.resolved` in the Vapor example directory.
Add the example to the NOTICE.txt file.
The Vapor example builds with the latest versions of its dependencies.
Built and ran the test example locally.

Examples: Update the Vapor example

---

.github/workflows/pull_request.yml
Tests/ContainerRegistryTests/ImageReferenceTests.swift

The smoke tests need a registry as a test fixture.   We don't yet have that but until we do we can still run the other tests.
Enable the `unit-test` shared CI workflow, with a filter.
A subset of tests will run on each pull request.   This will ensure that the code builds and some functionality is exercised for each pull request.
Ran the tests locally with `act pull_request`.

ci: Enable a subset of the unit tests

---

Package.swift
Sources/ContainerRegistry/AuthHandler.swift
Sources/ContainerRegistry/Blobs.swift
Sources/ContainerRegistry/CheckAPI.swift
Sources/ContainerRegistry/HTTPClient.swift
Sources/ContainerRegistry/Manifests.swift
Sources/ContainerRegistry/RegistryClient.swift
Sources/containertool/Extensions/Errors+CustomStringConvertible.swift

Swift HTTP Types provides currency types for HTTP clients and servers, which can be used with URLSession and AsyncHTTPClient.
Generally speaking, we try to keep Swift Container Plugin's dependencies to a minimum because each dependency increases the initial build time and also increases the chance of a version conflict with the project which is trying to use the plugin.   However `swift-http-types` is quite a small package and offers some nice ergonomic improvements over `URLRequest`/`URLResponse`, such as enums for HTTP status codes.
Switch all uses of `URLRequest`/`URLResponse` to `HTTPRequest`/`HTTPResponse`
The unit and integration tests continue to pass.

ContainerRegistry: Switch to swift-http-types

---

README.md

The package is now indexed by Swift Package Index, so we can link to the DocC-generated documentation pages hosted there.

Readme: Add Swift Package Index badges

---

Examples/HelloWorldHummingbird/.gitignore
Examples/HelloWorldHummingbird/Package.resolved
Examples/HelloWorldHummingbird/Package.swift
Examples/HelloWorldHummingbird/Sources/main.swift
NOTICE.txt

Having simple "getting started" examples is helpful for new users.   Some users may be more familiar with Hummingbird instead of Vapor.
Adds another example, using Hummingbird, and links it into the documentation.
New users who want to use Hummingbird can start from a tested starting point.
Built and deployed the example locally, and ran the soundness checks.

Examples: Add a Hello World example using Hummingbird

---

.github/workflows/pull_request.yml
NOTICE.txt
scripts/run-integration-tests.sh

The integration tests (`SmokeTests`) are not currently run on PRs because they require an instance of the container registry to be available.
Add a custom job which runs `registry` as a service container.
Integration tests will be run for every pull request.   The integration test job also runs the tests run by the unit tests job, but the duplication is not very costly. 
All tests continue to pass.

ci: Enable smoke tests

---

Sources/containertool/containertool.swift

The `--default-registry` parameter (also set by the `CONTAINERTOOL_DEFAULT_REGISTRY` environment variable) allows a default registry address to be specified for unqualified image names.   For example, the following uploads should be equivalent:
`containertool --default-registry myregistry.com --repository myrepo/myimage --from baserepo/baseimage`
`containertool --repository myregistry.com/myrepo/myimage --from baserepo/baseimage`
However the default registry was only being applied when fetching the base image (the `--from` parameter) and not when pushing the final image (the `--repository` parameter).
The default registry parameter is now used when pushing the final image.
Pushes to unqualified repositories will work properly.
Manually tested `containertool` uploads with a variety of …

containertool: Use the default registry parameter for image uploads

---

Examples/HelloWorldHummingbird/Package.resolved

Update Package.resolved, to pick up an important fix in swift-async-algorithms 1.0.2 which may prevent a crash in Hummingbird.
Update Package.resolved in the Hummingbird example.
The example will use newer dependencies.
The crash is intermittent but seems to happen after the server has been idle.   A server built with the new pins has been idle without crashing for much longer than a server built with the old pins was able to run.

Examples: Update Package.resolved for Hummingbird

---

.github/workflows/pull_request.yml
.spi.yml

`swiftlang/github-workflows` is the final home for the shared soundness workflows which started in `apple/swift-nio`.
Use the soundness workflow from `swiftlang/github-workflows`.
Fix complaints from the new YAML linter step.
We will pull the shared workflow from the correct final location, so we will continue to receive updates.
CI continues to pass.

ci: Use the shared soundness workflow from swiftlang/github-workflows

---

Sources/ContainerRegistry/Blobs.swift
Sources/ContainerRegistry/Tags.swift

`swift-http-types` provides enums giving readable names for HTTP error codes.   We should use these enums everewhere.
Fix a few places where raw HTTP error codes were still being used.
The code is more consistent.   No functional change.

ContainerRegistry: Fix a few requests which were not using swift-http-types error codes 

---

.github/workflows/pull_request.yml

Upstream has removed the 5.8 configuration, so setting it causes the runners to fail.
https://github.com/apple/swift-nio/commit/c16420c4a7e026174e4eb373953a8eae41a7a4a8#diff-c91058a32040621ac54d6ea4194b302a420b7849f6e8561920d23a0e97acf69a
Remove Swift 5.8 configuration, add Swift 6.0 configuration.
Actions will run again.   Currently they fail with 'startup error'.
Check that actions-based tests can start again.

ci: Remove Linux 5.8 configuration

---

Sources/ContainerRegistry/Manifests.swift

If the manifest blob's `mediaType` is set, the distribution spec requires that the HTTP `Content-Type` used to upload the manifest should match it.
In `putManifest`, use the blob's `mediaType` if it is set;  otherwise default to `manifest.v1`.
If a manifest uses a different media type, it will be passed through to the registry.   This might happen when copying a base image, which could have been created using the older manifest type.
Automated tests continue to pass.  Also tested manually with different registries.

ContainerRegistry: Pass through the manifest's mediaType, if set

---

Sources/ContainerRegistry/CheckAPI.swift

The registry indicates that it supports the v2 protocol by returning a [200 OK response](See https://github.com/opencontainers/distribution-spec/blob/main/spec.md#determining-support)
Many registries also set `Content-Type: application/json` and return empty JSON objects in their responses but this is not required and some, such as ECR, return empty responses.
Do not require the API check response to contain an empty JSON object.
Pushing to ECR will no longer fail with an `"The given data was not valid JSON."` error message. 
Automated tests continue to pass, tested manually with ECR.

ContainerRegistry: A /v2/ protocol check response is allowed to be empty

---

Sources/ContainerRegistry/Manifests.swift

According to distribution spec, the manifest `PUT` response [MUST contain a Location header](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pushing-manifests) providing a URL from which the saved manifest can be downloaded. The same requirement applies to blob `PUT`s.   However some registries return URLs which cannot be fetched, and ECR does not set this header at all. 
The location header is not currently of critical important.   If the header is not present, we can create a suitable value based on the spec for [manifest downloads](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#pulling-manifests).
Generate a suitable manifest location URL when the registry does not provide one.
Uploads to ECR will no longer fail because of the missing …

ContainerRegistry: Tolerate missing `Location` header in the manifest PUT response

---

Sources/ContainerRegistry/Blobs.swift
Sources/ContainerRegistry/CheckAPI.swift
Sources/ContainerRegistry/HTTPClient.swift
Sources/ContainerRegistry/Manifests.swift
Sources/ContainerRegistry/RegistryClient.swift
Sources/ContainerRegistry/Tags.swift

`RegistryClient.executeRequestThrowing` currently takes an `HTTPRequest` struct parameter and executes it using the underlying `HTTPClient`.   It augments `HTTPClient` by handling authentication challenges and decodes JSON error responses, but the use of `HTTPRequest` means that the caller is responsible for details such as generating the full distribution endpoint URL.   Giving `RegistryClient` its own abstract operation type frees the caller from dealing with these internal details.
The struct can also be passed easily anywhere the details of the operation are required, making future improvements easier.   For instance, if an operation causes an error, the original operation struct could be attached to the error making all its details available to the error handler.
Add a struct which …

ContainerRegistry: Add a struct to represent a registry operation

---

Sources/ContainerRegistry/AuthHandler.swift
Sources/ContainerRegistry/CheckAPI.swift
Sources/ContainerRegistry/HTTPClient.swift
Sources/ContainerRegistry/RegistryClient.swift
Tests/ContainerRegistryTests/AuthTests.swift
Tests/ContainerRegistryTests/SmokeTests.swift

Currently, `ContainerRegistry` handles authentication lazily.   First it tries an unauthenticated request.   If the registry responds with a challenge, `ContainerRegistry` gets a suitable credential from `.netrc` or from an authentication service and re-tries the request.
When pushing large blobs to some registries, the client can get stuck in a state where it has received an authentication challenge but is still waiting to finish the blob upload.   The symptoms are that metadata uploads and very small image layers can be uploaded, but pushing larger images stalls and times out, as reported in #17.
When pushing large blobs, the registry's `401` challenge arrives after the client has sent some of the blob data, but before it has completed the upload.   With some registries, `URLSession` …

ContainerRegistry: Remember initial auth challenge and send credentials eagerly

---

Sources/containertool/containertool.swift

The convenient `Date.now.ISO8601Format()` method was not present on Linux in earlier versions of Swift, but is available in Swift 6.0.
Use `Date.now.ISO8601Format()` instead of creating a separate formatter.

containertool: Date.now.ISO8601Format is available on Linux on Swift 6.0

---

Package.swift
Sources/ContainerRegistry/Blobs.swift
Sources/ContainerRegistry/ImageManifest+Digest.swift

`swift-crypto` provides a common cryptography interface on macOS and Linux.   On macOS it defers to CryptoKit, and although the files in the library must all be processed the compilation time is minimal.
In the past, on slower machines, avoiding processing `swift-crypto` on macOS seemed to improve build times by a few seconds.   Currently the cost of processing these files is negligible, and using `swift-crypto` on Linux and macOS allows conditional includes to be removed.
Always depend on `swift-crypto` in `Package.swift`
Replace conditional imports of `CryptoKit` with unconditional imports of `Crypto`.
Automated tests continue to pass.

ContainerRegistry: Unconditionally depend on swift-crypto

---

.github/PULL_REQUEST_TEMPLATE.md

Motivation
----------
The Git CLI ignores commit message lines starting with # as comments,
so editing commits causes heading lines starting ### to be lost.
Modifications
-------------
Change the pull request template to use underlines instead of ###.
Result
------
Headings will not be lost when commits are edited using the `git` CLI.
Headings will now be H2 rather than H3, because there is no alternative
syntax for H3.
Test Plan
---------
Submitted this PR using the new syntax.

github: Use alternative heading syntax in pull request template 

---

Package.swift
Sources/containertool/gzip.swift
Tests/containertoolTests/ZlibTests.swift

Motivation
----------
Packaging the same binary using the same version of `containertool` produces different application image layers on macOS and Linux:
```
linux% swift run containertool --verbose --repository registry.test:5000/hello hello-world --from scratch
...
Uploading application layer
application layer: sha256:54a282d5cd082320d2d4976e7d9a952da46e3bc4bab3ce1e0b3931ccf945b849 (80394382 bytes)
image configuration: sha256:fdcb887ef6e27a09456419b03b1d8353b15d68d088b8ea023f38af892fca69be (462 bytes)
...
macos% swift run containertool --verbose --repository registry.test:5000/hello hello-world --from scratch
...
Uploading application layer
application layer: sha256:08a21093e79423c17b58325decc48d7196481ed55276c2d168de23a75d38727e (80394382 bytes)
image configuration: …
```

containertool: Use same gzip headers on Linux and macOS

---

.github/workflows/pull_request.yml
Examples/HelloWorldHummingbird/Package.swift

Motivation
----------
For each pull request, the CI runs a number of test suites:
* Soundness: these are static checks of formatting, language and so on
* Unit tests: these check individual library functions in isolation
* Integration tests: these check individual registry library functions against a test registry instance
* Swift 6 Language Mode: this checks that the project compiles with Swift 6
These are all unit or integration tests;  there are no complete system tests to exercise the `build-container-image` plugin, or that the examples work.   It is difficult to test the `build-container-image` plugin in XCTest, but with GitHub Actions we can work through all the steps of building and deploying one of the examples, including using a Swift SDK.    This will cover all the major parts …

tests: Build and run examples as end to end tests

---

Sources/containertool/containertool.swift

Motivation
----------
The registry is a content-addressable store in which objects are identified by their hashes.   Many objects, such as image manifests, contain timestamp fields.   A difference in a timestamp field will cause otherwise identical objects to have different hashes, causing a variety of problems:
* an image cannot be verified by rebuilding it from the same original parts and comparing the result
* the registry cannot completely deduplicate two images with almost identical contents because their hashes do not match, wasting storage and network bandwidth (some block-level deduplication may still be possible, but clients which already have one image will have to pull the other in its entirety)
These problems can be avoided by setting timestamp fields to fixed values, often …

containertool: Use epoch date in image metadata

---

.github/workflows/endtoend_tests.yml
.github/workflows/main.yml
.github/workflows/pull_request.yml

Motivation
----------
It is very important that the example projects work when a new user tries them, but upstream changes might cause them to stop working even if nothing changes in this project.   This PR adds a job to run the tests daily to identify such problems as early as possible.
Modifications
-------------
* Extract the end to end tests into a reusable workflow
* Add a new action to run the tests daily, and for every push to main
Result
------
Tests will be run periodically.
Test Plan
---------
The existing tests continue to pass - this PR will run them more often.

tests: Test main daily

---

Sources/ContainerRegistry/Blobs.swift

Motivation
----------
In the 'Post then Put' blob upload method
(https://github.com/opencontainers/distribution-spec/blob/main/spec.md#post-then-put)
the client starts by making a POST request asking the registry to
start an upload session.   The registry responds with a URL to which
the client should PUT the blob.   The upload location might not be
provided by the registry server, allowing the registry to offload
storage to a different service.
Until now all registries we have encountered have returned absolute
upload URLs, however GHCR returns a relative URL causing uploads to
fail as reported in https://github.com/apple/swift-container-plugin/issues/43.
Modifications
-------------
If the registry returns a relative URL, startBlobUpload() rewrites it
to be an absolute URL referring to …

ContainerRegistry: The registry may return a relative blob upload URL

---

Tests/ContainerRegistryTests/AuthTests.swift
Tests/ContainerRegistryTests/ImageReferenceTests.swift
Tests/ContainerRegistryTests/SmokeTests.swift
Tests/containertoolTests/ZlibTests.swift
scripts/run-integration-tests.sh

Motivation
----------
swift-testing offers a more convenient way to write test cases.   For
instance, it makes table-driven tests much easier to write than XCTest.
Modifications
-------------
This commit rewrites the existing XCTest test cases to use swift-testing. It is a mechanical translation using the rules in:
https://developer.apple.com/documentation/testing/migratingfromxctest
It does not try to adapt the style of the tests to `swift-testing`.
Result
------
The tests run using `swift-testing` with minimal changes. A future change will adapt them to make better use of the new framework's facilities.
One immediate improvement is that the `swift-testing` tests can be run with the OSS Swift toolchain on macOS.  `XCTests` cannot, because the framework is not included in the OSS …

tests: Mechanically convert to swift-testing

---

Sources/ContainerRegistry/ImageReference.swift
Tests/ContainerRegistryTests/ImageReferenceTests.swift

Motivation
----------
`ImageReference.testReferences` tests is a table-driven test which iterates over a list of test cases.   Under `XCTest` it was implemented as a single test containing a loop, but with `swift-testing` the loop can be moved outside the test.   This makes it easier to see that multiple test cases are being run and to diagnose problems.
Modifications
-------------
`ImageReference.testReferences` now uses `@Test(arguments: ...)` to iterate over the existing test list.
Result
------
Test reports are more detailed. 
Test Plan
---------
All tests continue to pass.

tests: Convert ReferenceTests to `swift-testing` parameterised tests

---

.github/workflows/pull_request.yml

Motivation
----------
The shared unit test workflow has been updated to run on Swift 6.1 nightlies: https://github.com/apple/swift-nio/pull/3076
A new `linux_nightly_6_1_arguments_override` parameter must be set to skip the smoke tests when running unit tests in CI.
Modifications
-------------
Define `linux_nightly_6_1_arguments_override` to ignore smoke tests.
Remove `linux_nightly_6_0_arguments_override` which is no longer used.
Result
------
Tests, including the daily test runs, will pass again.
Test Plan
---------
This fixes a test failure caused by the upstream shared workflows being changed.   All tests now pass again.

ci: Skip smoke tests for Swift 6.1

---

.github/workflows/interop_tests.yml
.github/workflows/pull_request.yml
Sources/containertool/containertool.swift

Motivation
----------
containertool currently adds the app layer to the beginning of the
layer stack array in the manifest. This results in the app layer
being the first to be unpacked, with the others stacked on top. We
can show this by adding a plain text file as the executable. If we
stack another layer on top with a file of the same name, it should
replace the underlying one but it does not:
echo first > bar
swift run containertool --repository localhost:5555/bar bar
podman run --pull=always -it --rm --entrypoint=cat localhost:5555/bar:latest bar
echo second > bar
swift run containertool --repository localhost:5555/bar bar --from localhost:5555/bar:latest
podman run --pull=always -it --rm --entrypoint=cat localhost:5555/bar:latest bar
Currently containertool is only used to add the …

container: Add application layer to the correct end of the layer stack

---

.github/workflows/interop_tests.yml

Motivation
----------
The layering tests sometimes fail with 400 errors from the registry.   This error could be caused by pulling the underlying base image from Docker Hub, although the logs do not give enough information to be certain.
We don't need to run the container image in order to check that the payload file is being layered correctly.    This would avoid the need to pull `swift:slim`, reducing the risk of external systems causing test failures.
Modifications
-------------
Build the test image on scratch.
Instead of running the container and using `cat` to check the contents of `/payload`, create a container from the image and copy `/payload` out, without starting the container.
Result
------
The layering tests should be less susceptible to failures caused by external systems. …

tests: Build the layering test images on scratch to avoid pulling swift:slim

---

Plugins/ContainerImageBuilder/Pipe+lines.swift
Sources/ContainerRegistry/Blobs.swift
Sources/ContainerRegistry/ImageManifest+Digest.swift
Sources/Tar/tar.swift
Sources/containertool/Extensions/RegistryClient+Layers.swift
Tests/ContainerRegistryTests/SmokeTests.swift
Tests/TarTests/TarUnitTests.swift
Tests/containertoolTests/ZlibTests.swift

Motivation
----------
In many places we import a whole module but only use one or two structs or classes.   In these cases, importing just the parts we need makes dependencies clearer.
Modifications
-------------
* Where only one definition is used, constrain the import statement to only that definition.
* Remove a couple of Foundation imports which were completely unused.
Result
------
No functional change.  Dependencies are clearer.
Test Plan
---------

plugin, containertool: Remove unnecessarily broad Foundation imports

---

Package.swift
Sources/containertool/containertool.swift

Motivation
----------
Commit 9a3e7af92e3093f41deb8c83ed9fd25e59a3de90 configured `swift-format` to retain existing line breaks to make complex test case definitions easier to read.   
Modifications
-------------
This commit reformats complex definitions in `Package.swift` and `containertool` to make more readable.
Result
------
`Package.swift` and `containertool` will be easier to read and modify.   Diffs will be easier to read because partial line changes will be less likely.
Test Plan
---------

Package.swift, containertool: Make multi-line definitions clearer

---

Sources/Tar/tar.swift
Tests/TarTests/TarUnitTests.swift

Motivation
----------
Tar archives are stored sequences of 512-byte blocks, so archive members must be zero-padded to the nearest whole number of blocks.   The current padding calculation incorrectly adds a full 512-byte padding block if the member already finishes on a block boundary.
The tar end of file marker is defined as two consecutive empty blocks:
https://www.loc.gov/preservation/digital/formats/fdd/fdd000531.shtml
However interoperability testing with the system tar binary shows that a single unnecessary empty block will be interpreted as the end of the file.
Modifications
-------------
The padding calculation now correctly avoids zero-padding a file which is already a whole number of blocks in length.
Result
------
* Tar archives produced by the `Tar` module will match the out …

tar: Only pad partially-filled blocks

---

Sources/Tar/tar.swift
Tests/TarTests/TarUnitTests.swift

Motivation
----------
The tar writer is able to write a single file into a tar archive.   This is enough to build a container image around a single executable, but adding resource bundles (issue #48) requires the ability to write multiple files, directories and possibly symlinks into the archive.   This commit begins to refactor the tar writer to support this.   A future commit will add interoperability testing to ensure that more complex archives can be unpacked correctly.
Modifications
-------------
* Add a TarHeader struct representing a standard tar archive member
* Convert type flags to an enum
* Wrap fields in a namespacing enum
Result
------
No functional change.   Tar writer is more modular, easier to test and extend.
Test Plan
---------
Existing tests continue to pass.

tar: Refactor tar writer, add a struct to represent tar headers

---

.github/workflows/pull_request.yml
Tests/TarTests/TarInteropTests.swift

Motivation
----------
Tar archives must be read by a variety of other tar implementations.   As the archives produced by `containertool` become more complex, we need interoperability tests to make sure they still comply with the expectations of readers.
Modifications
-------------
* Add a new TarInteropTests suite which generates a variety of tar archives and verifies that BSD tar can read them.
* Add tests which demonstrate rules of the tar format and show how BSD tar deal with corrupt archives
Result
------
The output of the tar writer will be tested to ensure that BSD tar can read it.
Test Plan
---------
* Added new interoperability tests
* Existing tests continue to pass

tests: Add interoperability tests using the system's tar

---

.github/workflows/integration_tests.yml
.github/workflows/main.yml
.github/workflows/pull_request.yml

Motivation
----------
The definition of the integration test job was duplicated in `main.yml` and `pull_request.yml`.   When changes were made in one but not the other, the pull request CI job passed but the main CI job later failed after the pull request had been merged.
Modifications
-------------
* The integration test job has been moved to a shared file which `main.yml` and `pull_request.yml` can both include.
Result
------
If the pull request job succeeds, the main job should also succeed.
Test Plan
---------
Tests on main branch pass again.

ci: Use a shared definition of integration tests in pull request and main jobs

---

.github/workflows/main.yml

Motivation
----------
The main unit test job needs to match the pull_request unit test job.   Both jobs depend on `swift-nio`'s shared unit test job, so it's unclear whether this can be abstracted further.
Modifications
-------------
* Update the `--skip` parameters in `main.yml` to match `pull_request.yml`
Result
------
The results of `main` unit test job should match those of the `pull_request` unit test job.
Test Plan
---------
Unit tests run on the main branch should pass again.

ci: Skip Tar interop tests in main unit test job

---

Sources/containertool/Extensions/ELF+containerArchitecture.swift
Sources/containertool/containertool.swift

Motivation
----------
All extensions defined in `containertool` should be in the `Extensions` subdirectory.
Modifications
-------------
Move `ELF.containerArchitecture` extension to `Extensions`.
Result
------
All `containertool` extensions can be found in one place.
Test Plan
---------

containertool: Move ELF architecture translation extension to Extensions

---

Sources/Tar/tar.swift
Tests/TarTests/TarInteropTests.swift
Tests/TarTests/TarUnitTests.swift

Motivation
----------
The tar writer currently provides helper functions which can create tar archives containing single executable files.   In order to include resource bundles in container images (#48) the tar writer must be able create archives containing multiple files and directories.
Modifications
-------------
* A new `Archive` type representing a tar archive allows multiple files to be added before being written out as an array of bytes.
* Helper functions allow files and directories to be added to the archive.
Result
------
The tar writer is able to create archives containing files and directories.
Test Plan
---------
New tests exercise creating archives containing multiple members, including directories.

tar: Add support for archiving directories

---

.github/workflows/integration_tests.yml
Plugins/ContainerImageBuilder/main.swift
scripts/test-plugin-output-streaming.sh

Motivation
----------
`containertool` produces its normal output in single writes of less than PIPE_BUF bytes, which should be delivered atomically through the pipe to the plugin:
> Reading or writing pipe data is atomic if the size of data written is not greater than PIPE_BUF. This means that the data transfer seems to be an instantaneous unit, in that nothing else in the system can observe a state in which it is partially complete. Atomic I/O may not begin right away (it may need to wait for buffer space or for data), but once it does begin it finishes immediately.
https://www.gnu.org/software/libc/manual/html_node/Pipe-Atomicity.html
Progress messages written in this way are displayed correctly.   Unfortunately error output from `swift-argument-parser` is delivered in smaller chunks …

plugin: handle chunks of output correctly

---

Sources/Tar/tar.swift
Sources/containertool/containertool.swift

Motivation
----------
Libraries should have as few dependencies as possible.   `Tar` only depends on Foundation because of a convenience wrapper function which can easily be handled in the caller.
Modifications
-------------
* Remove the `public func tar(_ data: Data, filename: String) throws -> [UInt8]` wrapper
Result
------
No functional change to `containertool`.  `Tar` no longer depends on Foundation.
Test Plan
---------
Existing tests continue to pass.

tar: Remove dependency on Foundation

---

.github/workflows/main.yml
.github/workflows/pull_request.yml

Motivation
----------
Swift NIO's unit test matrix job has been [updated for Swift 6.1](https://github.com/apple/swift-nio/commit/b8c446368dfe7e612df3f283861891e8208accbe), so additional override flags must be defined.
Modifications
-------------
Define `linux_6_1_arguments_override` for pull requests and the scheduled build on main.
Result
------
Tests with Swift 6.1 will pass.
Test Plan
---------
Existing tests pass again.

ci: Add --skip flags for Swift 6.1 matrix job

---

Examples/HelloWorldHummingbird/Package.swift
Examples/HelloWorldHummingbird/Sources/App.swift
Examples/HelloWorldHummingbird/Sources/Application+build.swift

Motivation
----------
The [official Hummingbird examples](https://github.com/hummingbird-project/hummingbird-examples) split the server into a main entry point file and a separate build function.   Adopting the same structure makes this example more more familiar to users who are used to the official examples.
Modifications
-------------
Adopt the Hummingbird example structure for `HelloWorldHummingbird`
Result
------
The example works in the same way as before but has a more familiar structure for Hummingbird users.
Test Plan
---------
All tests continue to pass.

Examples: Adopt the structure used in hummingbird-examples

---

README.md

Motivation
----------
README.md is the first file new users see when they visit the repository.  It should be well-structured, so information is easy to find.
Modifications
-------------
* Split the existing documentation into better-named, hierarchical sections
* Document the dependency on Swift SDKs
Result
------
It will be easier for new users to find information.
Test Plan
---------
No functional change.  Existing tests continue to pass.

Readme: Restructure and clarify requirements

---

CONTRIBUTING.md

scripts/soundness.sh was deleted in #5 which moved CI to GitHub Actions.
resolves #96 
Remove the instruction to run `scripts/soundness.sh` from `CONTRIBUTING.md`.
Documentation no longer refers to nonexistent scripts.

docs: Update CONTRIBUTING to reference soundness checks and remove advice to run locally

---

Package.swift
Sources/ContainerImageBuilderPluginDocumentation/README.md

Makes it easier to preview documentation changes
* Add dependency on swift-docc-plugin
* Add detail on how to preview into the README within the documentation target
Documentation changes can be previewed by running the following command:
```
swift package --disable-sandbox preview-documentation --target ContainerImageBuilderPlugin
```

docs: Use swift-docc-plugin to preview documentation

---

README.md
Sources/swift-container-plugin/Documentation.docc/Adding-the-plugin-to-your-project.md
Sources/swift-container-plugin/Documentation.docc/Swift-Container-Plugin.md

Motivation
----------
Restructuring the documentation has left some broken links.
Modifications
-------------
* The examples link in the top level README should point to the documentation on Swift Package Index.
* The examples link in the top level DoCC page should point to the examples directory on GitHub.
Result
------
All links point to the correct pages.
Test Plan
---------
Tested manually.

docs: Fix broken examples links

---

Sources/swift-container-plugin/Documentation.docc/authentication.md

Motivation
----------
Public container registries often have more complex authentication schemes than privately-hosted registries.   For instance, they might use authentication tokens instead of passwords, or authentication might be a separate service from the registry.   Users will benefit from being able to refer to examples which show suitable `.netrc` entries, with information about how to generate tokens and avoid common problems.
Modifications
-------------
Add example configurations for a number of popular container registries.
Result
------
New users can refer to concrete examples of `.netrc` stanzas for popular container registries, along with outline instructions explaining how to generate the necessary authentication tokens.
Test Plan
---------
Manually tested the instructions. …

docs: Add example authentication configurations

---

Package.swift
Sources/containertool/Documentation.docc/containertool.md
Sources/containertool/containertool.swift
Sources/swift-container-plugin/Documentation.docc/Adding-the-plugin-to-your-project.md
Sources/swift-container-plugin/Documentation.docc/Swift-Container-Plugin.md
Sources/swift-container-plugin/Documentation.docc/build.md
Sources/swift-container-plugin/Documentation.docc/run.md
Sources/swift-container-plugin/README.md

Motivation
----------
As with authentication configuration, it is useful for new users to be able to refer to concrete examples showing how to use the plugin.
Modifications
-------------
* Add a section to the 'run' document showing how to build and run an image in one command.
* Add sections showing how to publish images to some popular public container registries.
Result
------
Users can refer to examples showing how to use the plugin to build and run images.
Test Plan
---------
Steps tested manually.
All automated tests continue to pass.

docs: Add examples of building and publishing images

---

.spi.yml
Examples/HelloWorldHummingbird/Package.swift
Examples/HelloWorldVapor/Package.swift
Examples/HelloWorldWithResources/Package.swift
README.md

Motivation
----------
The DoCC documentation was restructured substantially between 0.5.0 and 1.0.0, so the links in `README.md` are no longer correct.    The examples should also point to the new release. 
Modifications
-------------
* Update the links to the Swift Package Index documentation
* Update example project dependencies 
* Stop asking SPI to build the `containertool` documentation target 
Result
------
Documentation links will be correct once Swift Package Index builds the new release.
Test Plan
---------
All existing tests continue to pass.

docs: Update documentation links and examples after 1.0.0 release

---

README.md
Sources/swift-container-plugin/Documentation.docc/Swift-Container-Plugin.md

Motivation
----------
By default, Swift Package Index shows the documentation for the latest release.   This still has the `containertool` documentation target in `.spi.yml`, which is causing the left-hand navigation bar (the curation) to show the topics for `containertool` even though the main content is the Swift Container Plugin Documentation.
This should be resolved when the next release is tagged, but in the meantime linking to the `main` branch documentation will cause users to see the most up-to-date documentation with the correct navigation bar.
Modifications
-------------
Links to the SPI documentation in `README.md` point to the `main` branch.
Result
------
Users should see the latest documentation, with the correct navigation bar.
Test Plan
---------
All …

docs: Point to main branch documentation on Swift Package Index

---

Sources/containertool/containertool.swift

Motivation
----------
Most of `containertool`'s work is handled in its `run()` method.
* It starts by processing arguments and assigning defaults;
* It then creates `RegistryClient` instance;
* Finally it assembles the image and uploads it.
All of this work takes place inline, in a single method called by `SwiftArgumentParser`.   This complicates maintenance and makes it difficult to test the image assembly process without writing full end-to-end tests.
Modifications
-------------
* Extract the image building process into a standalone function.
* `run()` is only responsible for processing arguments and creating the clients needed by the build function.
Result
------
The image build process will be easier to test and maintain.
It will be easier to add more complex argument handling, such …

containertool: Separate command line option processing from image publishing

---

Sources/containertool/containertool.swift

Motivation
----------
Many `containertool` options have default values set by environment variables.
* if the option flag is set on the command line, the command line value is used
* otherwise, if the option flag is not set, the environment variable value is used
* otherwise, a hard-coded default is used
This pattern is quite convenient, but there are some drawbacks.   For example:
* the default value declarations complicate the definition of new arguments.
* default values appear in the `--help` output: for some options, such as default base image, this is desirable, but for others, such as credentials, it is not.
Some options do not fit this pattern well.  For instance, `containertool` tries to detect the architecture of the executable it is packaging so it can try to choose a …

containertool: Don't set environment-variable defaults in parser

---

Sources/containertool/containertool.swift

Motivation
----------
The `--username` and `--password` options allow default credentials to be defined.   These are used if a corresponding entry cannot be found in `.netrc`, or if the `--disable-netrc` flag is set.    (`--username` and `--password` should possibly be renamed to `--default-username` and `--default-password` to make this clearer.)
Specifying passwords as command line arguments is generally discouraged because they will then be visible in the the output of tools such as `ps` and `top`.   Providing credentials in environment variables avoids this problem, although there may still be other ways for users on the same machine to discover their values.
Environment variables are also more convenient than `.netrc` when uploading to registries which use short-lived credentials, …

containertool: Read default username and password from the environment

---

README.md

Motivation
----------
By default, Swift Package Index shows the documentation for the latest release.   In release 1.0.0, `containertool` was still the first target in `.spi.yml`, which caused the left-hand navigation bar (the curation) to show the topics for `containertool` even though the main content is the Swift Container Plugin Documentation.
As a temporary work-around, #112 changed links from README.md to point to SPI's documentation for the `main` branch.   This caused the updated `.spi.yml` to be used and the correct curation to be shown, but also meant that unreleased features could not be documented because the live documentation would diverge from what had been released.
Version 1.0.1 has now been released, with some refactoring and documentation changes.   Links in `README.md` …

docs: Link to latest release documentation on Swift Package Index

---

Sources/containertool/containertool.swift
Sources/swift-container-plugin/Documentation.docc/build-container-image.md

Motivation
----------
The `--username` and `--password` options define default values which are used if no suitable credentials can be found in `.netrc`.  Their current names could imply that they override other sources of credentials - the help originally said this was the case (#123).   Renaming them to `--default-username` and `--default-password` reduces the risk of misunderstanding.
Modifications
-------------
* Rename the `--user` and `--password` options to `--default-user` and `--default-password`.
* Add checks to warn that the old versions are deprecated, and fail if both are provided together.
* Hide the old options from `--help` and remove them from the manual page
* Rename the environment variable versions of these options.   The environment variable change had not yet been …

containertool: Rename --username/password to --default-username/password

---

Examples/HelloWorldHummingbird/Package.swift
Sources/containertool/containertool.swift
Sources/swift-container-plugin/Documentation.docc/build-container-image.md
scripts/test-plugin-output-streaming.sh

Motivation
----------
It is currently only possible to set the destination repository by specifying the mandatory `--repository` flag.   Setting the repository from an environment variable can be more convenient in scripts and in the terminal - the destination repository can be set once and inherited by all further builds in the same shell.
Modifications
-------------
* `--repository` is no longer a mandatory argument.
* A new `CONTAINERTOOL_REPOSITORY` environment variable is used if `--repository` is not set.
Fixes #100 
Result
------
Either `--repository` or `CONTAINERTOOL_REPOSITORY` can be used to define the destination repository.   The command line flag takes precedence over the environment variable.
Test Plan
---------
All existing tests continue to pass.

containertool: Allow destination repository to be set by an environment variable

---

Sources/swift-container-plugin/Documentation.docc/build-container-image.md

Motivation
----------
Where command line options also have corresponding environment variables, the variables should be documented.   This PR documents a few variables which had been overlooked.
Modifications
-------------
Add descriptions of previously undocumented environment variables:
* `CONTAINERTOOL_ARCHITECTURE`
* `CONTAINERTOOL_DEFAULT_USERNAME`
* `CONTAINERTOOL_DEFAULT_PASSWORD`
Result
------
* All current configuration variables are documented.
Test Plan
---------
* No functional change.
* All existing tests continue to pass.

docs: Add undocumented environment variables to build-container-image manual

---

Sources/containertool/containertool.swift
Sources/swift-container-plugin/Documentation.docc/build-container-image.md

Motivation
----------
Arranging related options together in groups makes it easier for users to find relevant options.   This will be even more beneficial as more options are added (e.g. #91).
Modifications
-------------
* Arrange `containertool`'s command line options into related groups with headings.
* Update `build-container-image` manual page to match the new groupings.
Result
------
* Users will be able to find help for specific options more easily.
* Grouping options together may also help them to discover new options related the tasks they are trying to achieve.
Test Plan
---------
* No functional change. 
* All existing tests continue to pass.

containertool: Arrange options into related groups

---

Sources/ContainerRegistry/AuthHandler.swift
Sources/ContainerRegistry/Blobs.swift
Sources/ContainerRegistry/ImageReference.swift
Sources/ContainerRegistry/Manifests.swift
Sources/ContainerRegistry/RegistryClient.swift
Sources/ContainerRegistry/Tags.swift
Sources/containertool/Extensions/Errors+CustomStringConvertible.swift
Sources/containertool/Extensions/RegistryClient+CopyBlobs.swift
Sources/containertool/Extensions/RegistryClient+Layers.swift
Tests/ContainerRegistryTests/ImageReferenceTests.swift
Tests/ContainerRegistryTests/SmokeTests.swift

Motivation
----------
`ImageReference` does not check for illegal characters in parsed image references.   This means that `containertool` will send illegal image names to the registry.   The registry will reject them, but the error message might not explain why, so a generic error message will be printed.   Runtimes reject illegal image references immediately, without sending them to the registry. 
Modifications
-------------
* Introduce a `Repository` wrapper type
* Check validity when constructing the `Repository`
* Change the low-level API functions to accept `Repository` instead of `String`.
Result
------
It is impossible to create a `Repository` object containing a malformed name, because the constructor checks the string value.   It is impossible to send a malformed name to the …

ContainerRegistry: Reject invalid repository names

---

Sources/ContainerRegistry/Blobs.swift
Sources/ContainerRegistry/Manifests.swift
Sources/ContainerRegistry/RegistryClient+ImageConfiguration.swift
Sources/ContainerRegistry/RegistryClient.swift
Sources/ContainerRegistry/Tags.swift

Motivation
----------
Return type overloads can be puzzling for new readers because the same function call returns a different type depending on where it is called.  In some cases a type annotation is needed at the call site, but when the overloaded function is the final call in another function the compiler can infer the type, so the reader needs to know to check the type of the enclosing function.
In addition, in a future pull request we will need access to the underlying data returned by the HTTP client, in order to verify digests and create `ContentDescriptor` objects.  This refactoring starts to prepare for that and makes the code easier to understand.
Modifications
-------------
* Remove return-type overloaded version of `executeRequestThrowing()`
* Remove return-type overloaded …

ContainerRegistry: Remove return-type overloaded client functions

---

Sources/ContainerRegistry/ImageReference.swift
Sources/ContainerRegistry/ImageSource.swift
Sources/ContainerRegistry/RegistryClient.swift
Sources/ContainerRegistry/ScratchImage.swift
Sources/containertool/Extensions/RegistryClient+publish.swift
Sources/containertool/containertool.swift
Tests/ContainerRegistryTests/ImageReferenceTests.swift

Motivation
----------
When the `--from scratch` option is used, `containertool` does not download the [scratch](https://hub.docker.com/_/scratch) from Docker Hub - instead it synthesizes a suitable empty image.   Currently this is handled by making the source client optional, but that causes `nil` checks to spread everywhere.   Now that we have the `ImageSource` protocol (#148) we can instead use a [null object](https://en.wikipedia.org/wiki/Null_object_pattern) which can only return an empty image.   This allows the `nil` checks to be removed and lets the same code path handle images built on real base images and the scratch base image.
Modifications
-------------
* Add `ScratchImage`, a null object implementing the `ImageSource` protocol
* Remove special cases previously needed to make …

containertool: Use a null object to represent scratch images

---

.github/workflows/main.yml

Motivation
----------
Swift NIO's unit test matrix job has been [updated for Swift 6.2](https://github.com/apple/swift-nio/pull/3374), so additional override flags must be defined.
Modifications
-------------
Define `linux_6_2_arguments_override` for pull requests and the scheduled build on main.
Result
------
Tests with Swift 6.2 will pass.
Test Plan
---------
Existing tests pass again.

ci: Add --skip flags for Swift 6.2 matrix job

---

.github/workflows/endtoend_tests.yml
.github/workflows/interop_tests.yml

Motivation
----------
End to end and integration tests are failing because the underlying Swift CI runner has been updated to use Swift 6.2 but these tests install the 6.1 release of the Static Linux SDK.
Modifications
-------------
Update end to end and integration workflows to install the the 6.2 release of the Static Linux SDK.
Result
------
All tests will pass again.
Test Plan
---------
All existing tests pass again.

ci: Runner now uses Swift 6.2;  update the Static SDK to match
